version: "3.8"

services:
  apkx-web:
    build:
      context: .
    image: apkx-web:compose
    container_name: apkx-web
    ports:
      - "9090:9090"
    environment:
      # Prefer smart root detection; pin explicitly if mounting project root
      - APKX_ROOT=/app
      # Optionally set a default Discord webhook
      # - DISCORD_WEBHOOK=
      # Or override individual paths if not mounting the whole root
      # - APKX_UPLOAD_DIR=/web-data/uploads
      # - APKX_REPORTS_DIR=/web-data/reports
      # - APKX_DOWNLOAD_DIR=/web-data/downloads
      # - APKX_PATTERNS_PATH=/config/regexes.yaml
    volumes:
      # Mount the project root for smart detection
      - ./:/app
      # If you prefer mounting only needed dirs, comment the line above and use:
      # - ./web-data:/web-data
      # - ./config:/config
    command: ["/usr/local/bin/apkx-web", "-addr", ":9090", "-mitm"]
    restart: unless-stopped

