name: Build and Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Prepare Release Files
        run: |
          # Create directories
          mkdir -p dist/linux
          mkdir -p dist/windows
          mkdir -p dist/darwin
          
          # Copy common files to each directory
          for dir in dist/*; do
            cp -r README.md LICENSE config "$dir/" || true
          done

      - name: Build Binaries
        run: |
          # Build for Linux
          GOOS=linux GOARCH=amd64 go build -o dist/linux/apkx ./cmd/apkx/main.go
          cd dist/linux
          tar czf ../apkx-linux-amd64.tar.gz *
          cd ../..
          
          # Build for Windows
          GOOS=windows GOARCH=amd64 go build -o dist/windows/apkx.exe ./cmd/apkx/main.go
          cd dist/windows
          zip -r ../apkx-windows-amd64.zip *
          cd ../..
          
          # Build for macOS
          GOOS=darwin GOARCH=amd64 go build -o dist/darwin/apkx ./cmd/apkx/main.go
          cd dist/darwin
          tar czf ../apkx-darwin-amd64.tar.gz *
          cd ../..

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.tar.gz
            dist/*.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}